# Generated by Django 3.2.12 on 2022-02-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=32, verbose_name='联系方式')),
                ('method', models.CharField(max_length=32, verbose_name='预期流转方式')),
                ('type', models.CharField(max_length=32, verbose_name='预期土地类型')),
                ('province', models.CharField(max_length=32, verbose_name='省份')),
                ('city', models.CharField(max_length=32, verbose_name='市')),
                ('countrySide', models.CharField(max_length=32, verbose_name='县/区')),
                ('value_min', models.CharField(max_length=32, verbose_name='预期价格下界')),
                ('value_max', models.CharField(max_length=32, verbose_name='预期价格上界')),
                ('year_min', models.CharField(max_length=32, verbose_name='年限下界')),
                ('year_max', models.CharField(max_length=32, verbose_name='年限上界')),
                ('size_min', models.CharField(max_length=32, verbose_name='预期土地范围下界')),
                ('size_max', models.CharField(max_length=32, verbose_name='预期土地范围上界')),
                ('dis', models.TextField(verbose_name='预期描述')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.TextField(max_length=32, verbose_name='用户姓名')),
                ('location', models.TextField(max_length=32, verbose_name='地区')),
                ('type', models.TextField(max_length=32, verbose_name='类型与用途')),
                ('size', models.TextField(max_length=10, verbose_name='面积')),
                ('mobile', models.TextField(max_length=11, verbose_name='联系方式')),
                ('ensure', models.BooleanField(verbose_name='是否电话核实')),
                ('value', models.TextField(max_length=30, verbose_name='价格')),
                ('year', models.TextField(max_length=5, verbose_name='流转年限')),
                ('date', models.DateTimeField(verbose_name='发布日期')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='图片名')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.land')),
            ],
        ),
    ]
